-- 022_seed_jogadores.sql
-- Recria a lista inicial de jogadores. Todas as senhas sao exatamente "123".

TRUNCATE TABLE jogadores RESTART IDENTITY CASCADE;

INSERT INTO jogadores (username, senha_hash, nome, posicao, is_admin, is_ativo)
VALUES
  ('dico',       '123', 'dico',       'lateral', true,  true),
  ('natal',      '123', 'natal',      'meia', true,  true),
  ('hees',       '123', 'hees',       'lateral', true,  true),
  ('knust',      '123', 'knust',      'lateral', true,  true),
  ('tadeu',      '123', 'tadeu',      'meia', true,  true),
  ('thiagao',    '123', 'thiagao',    'atacante', false, true),
  ('cadinho',    '123', 'cadinho',    'atacante', false, true),
  ('gualberto',  '123', 'gualberto',  'meia', false, true),
  ('andret',     '123', 'andret',     'zagueiro', false, true),
  ('jp',         '123', 'jp',         'lateral', false, true),
  ('vitor',      '123', 'vitor',      'atacante', false, true),
  ('victor',     '123', 'victor',     'zagueiro', false, true),
  ('tchuca',     '123', 'tchuca',     'meia', false, true),
  ('ed',         '123', 'ed',         'lateral', false, true),
  ('fil',        '123', 'fil',        'atacante', false, true),
  ('danilo',     '123', 'danilo',     'atacante', false, true),
  ('hugo',       '123', 'hugo',       'meia', false, true),
  ('marcelinho', '123', 'marcelinho', 'meia', false, true),
  ('bill',       '123', 'bill',       'zagueiro', false, true),
  ('gustavo',    '123', 'gustavo',    'meia', false, true),
  ('gian',       '123', 'gian',       'lateral', false, true),
  ('azeita',     '123', 'azeita',     'atacante', false, true),
  ('guto',       '123', 'guto',       'meia', false, true),
  ('dudu',       '123', 'dudu',       'meia', false, true),
  ('pedrinho',   '123', 'pedrinho',   'goleiro', false, true),
  ('joel',       '123', 'joel',       'lateral', false, true),
  ('rod',        '123', 'rod',        'lateral', false, true),
  ('cafuba',     '123', 'cafuba',     'meia', false, true),
  ('random1',    '123', 'random1',    'random', false, true),
  ('random2',    '123', 'random2',    'random', false, true),
  ('random3',    '123', 'random3',    'random', false, true),
  ('random4',    '123', 'random4',    'random', false, true),
  ('random5',    '123', 'random5',    'random', false, true),
  ('random6',    '123', 'random6',    'random', false, true),
  ('guilherme',  '123', 'guilherme',  'meia', false, true),
  ('caio',       '123', 'caio',       'meia', false, true),
  ('geilson',    '123', 'geilson',    'goleiro', false, true),
  ('rodrigo',    '123', 'rodrigo',    'goleiro', false, true),
  ('lucas',      '123', 'lucas',      'meia', false, true),
  ('giovanni',   '123', 'giovanni',   'meia', false, true),
  ('gabriel',    '123', 'gabriel',    'meia', false, true),
  ('luizinho',   '123', 'luizinho',   'meia', false, true),
  ('coala',      '123', 'coala',      'meia', false, true),
  ('joaofelipe', '123', 'Joao Felipe', 'meia', false, true),
  ('navas',      '123', 'navas',      'meia', false, true),
  ('thacio',     '123', 'thacio',     'goleiro', false, true),
  ('thiago',   '123', 'thiago',   'goleiro', false, true),
  ('wilner',     '123', 'wilner',     'meia', false, true),
  ('luizguilherme', '123', 'Luiz Guilherme', 'meia', false, true),
  ('poeys',      '123', 'poeys',      'meia', false, true),
  ('ramon',      '123', 'ramon',      'meia', false, true),
  ('dude',       '123', 'dude',       'meia', false, true),
  ('jorge',      '123', 'jorge',      'meia', false, true),
  ('luis',       '123', 'Luis',       'meia', false, true),
  ('victorguimaraes', '123', 'Victor Guimaraes', 'meia', false, true);